version: "2.1"
services:
    flaresolverr:
        # DockerHub mirror flaresolverr/flaresolverr:latest
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        environment:
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - LOG_HTML=${LOG_HTML:-false}
            - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
            - TZ=Europe/London
        ports:
            - "${PORT:-8191}:8191"
        networks:
            - laravel
        restart: unless-stopped

    cfbypass:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - flaresolverr
            - db
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - cfbypass
        networks:
            - laravel
        restart: unless-stopped

    db:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel
        ports:
            - "5432:5432"
        volumes:
            - ../db:/var/lib/postgresql/data
        networks:
            - laravel
        restart: unless-stopped

networks:
    laravel:
        driver: bridge


